### ISSUE TITLE
Performance indicators

### ISSUE THREAD

**Issue by shdotcom** [thiagodnf/r-nsga-ii#1]
Hi,
would you please include performance indicators such as, IGD and HV, for R-NSGA-II algorithm?
Thank you

**Comment by thiagodnf** [comment]
Hello @shdotcom 

I just submitted a new code. Now you can visualize the quality indicators. I am using the same idea used in jMetal.

Thanks for you feedback.

**Comment by shdotcom** [comment]
Hi thiagodnf,

Thank you for your prompt reply. 
Is it possible to use your [Analysis tool](https://github.com/thiagodnf/analysis) with this implementation of R-NSGA-II?

If you do not mind, is it possible to contact with you via email?
Thank you for your time.

**Comment by thiagodnf** [comment]
> Is it possible to use your Analysis tool with this implementation of R-NSGA-II?

Yes it is. You have to save the pareto-front to a file and use it in the tool. Just remember to follow the directory strucuture
